include "Dependencies.lua"

group "Dependencies"
		include "XYZEngine/vendor/glfw"
		include "XYZEngine/vendor/GLEW"
		include "XYZEngine/vendor/OpenAL-Soft"
		include "XYZEngine/vendor/freetype-2.10.1"
		include "XYZEngine/vendor/imgui"
		include "XYZEngine/vendor/imgui-node-editor"
		include "XYZEngine/vendor/ImGuizmo"
		include "XYZEngine/vendor/box2d"
		include "XYZEngine/vendor/optick"
		include "XYZEngine/vendor/ozz-animation"
		include "XYZEngine/vendor/OpenXR-SDK"
group ""

include "XYZEngine"
include "XYZEditor"	
include "XYZScriptCore"
include "XYZScript"
include "XYZNative"